version: "3.9"
services:
  database:
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=vema
    ports:
      - '27017:27017'