name: Vema Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test with Gradle
      run: chmod +x ./gradlew && ./gradlew test 
  
    - name: Test with SonarQube
      run: ./gradlew build sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
